### ISSUE TITLE
Create personel wikis

### ISSUE THREAD

**Issue by veyisTurgut** [bounswe/2021SpringGroup12#1]
Everybody create your own personal wiki pages, Burakcan Kazım will handle the rest.

- [x] Batuhan Tongarlak 
- [x] Gökay Yıldız 
- [x] Veyis Turgut 
- [x] Ömer Yılmaz 
- [x] İhsan Gökçül 
- [x] Burakcan Kazım Yeşil 
- [x] Refika Kalyoncu 
- [x] Kürşat Talha berk Yamanoğlu
- [x] Doğukan Türksoy

**Comment by ihsangkcl** [comment]
lol
