### ISSUE TITLE
Add completed parts to milestone#1 report.

### ISSUE THREAD

**Issue by ihsangkcl** [bounswe/2021SpringGroup12#109]
We will add the completed parts to milestone#1 report.

**Comment by veyisTurgut** [comment]
Solid work so far. Needs some review though. Please try to be consistent between headers.

**Comment by ihsangkcl** [comment]
We have completed adding old and newly completed parts to the Milestone Report 1. Reviewed and revised according to the feedbacks of other group members. [Here](https://github.com/bounswe/2021SpringGroup12/blob/master/deliverables/M1-Group12.pdf) is the final report.
