### ISSUE TITLE
Revising requirements to remove redundancy

### ISSUE THREAD

**Issue by veyisTurgut** [bounswe/2021SpringGroup12#115]
Deadline: 10.05.2021

TA Serdar Hoca e-mailed us a feedback about requirements, I will revise them regarding that e-mail.

Main concepts: 
* The features that users can see goes under "user reqs", otherwise "system reqs". 
* Try to be concise!
* Don't be repetitive.

**Comment by uskudarli** [comment]
This title is not descriptive. Should be something like

Revise requirements for structure and consistency.

**Comment by Refref18** [comment]
think you already finished?

**Comment by veyisTurgut** [comment]
hahaha
not yet :)

**Comment by veyisTurgut** [comment]
Change report:
* "content" word is removed from the requirements since users are not going to "post" anything.
* 1.1.3.7.4 "listed modifications" fixed
* "item" keyword is added to glossary. It stands for goals, subgoals and entities. And of course, entity stands for tasks, routines, questions, reflections.
*  1.1.3.16 and  1.1.3.17 fixed. 
* removed 2.2.2

Also removed most of the 1.2 System requirements to remove repetiton.

Still some review would be great! @Refref18 @ihsangkcl @batuhanovski

**Comment by ihsangkcl** [comment]
I reviewed briefly. It looks fine to me. Nice work 👍 
I will review in detail after this week. Because I'm so busy right now with the projects of other lectures:(
