### ISSUE TITLE
Unittest Import Problem

### ISSUE THREAD

**Issue by veyisTurgut** [bounswe/2021SpringGroup12#141]
When we try to run unittests in VSCode or Pycharm directly, we get the following error:
`ImportError: attempted relative import with no known parent package
`

Please checkout to "`buggy-testcase-suzan-hoca`" branch to test.

We found a way around for now to fix this problem, but we are worried that this will cause headaches during deployment phase since there will be no Pycharm. 

* Before we begin, to mark a directory:
  * Right click that directory from Project Files section in Pycharm.
  * You will see an option named "`Mark Directory As >`", click it.
  * Choose "`Sources Root`" option.
  * You can unmark the same way.
  * Its color will be turned to blue.

Ok, lets see some screenshots:
 
* Pycharm, marked "`main`" directory as "`Sources Root`", it works! 
![image](https://user-images.githubusercontent.com/47869761/120672681-313d2d80-c49b-11eb-8779-4f240e7956d6.png)

* Pycharm, run directly - nothing marked, error.
![image](https://user-images.githubusercontent.com/47869761/120672765-444ffd80-c49b-11eb-93ae-afa678df1b67.png)

* Vscode, I can't mark any directory as source, error:
![image](https://user-images.githubusercontent.com/47869761/120673225-a90b5800-c49b-11eb-9aa4-23345f848637.png)

**Comment by veyisTurgut** [comment]
Since I didn't know which account you use, I assigned both.

**Comment by veyisTurgut** [comment]
We solved the problem, solution is on Discord channel of BOUNSWE 2021 - Group 12. I will refactor the code and inform friends. I will also update here when I push the updated code.

**Comment by uskudarli** [comment]
Also, introduced the test_suite to general HTML reports of tests.
A good idea  to do coverage report too.

**Comment by veyisTurgut** [comment]
I pushed it: https://github.com/bounswe/2021SpringGroup12/pull/158
