### ISSUE TITLE
Change the api's which include special query

### ISSUE THREAD

**Issue by Refref18** [bounswe/2021SpringGroup12#150]
vchange the api which includes a key

**Comment by veyisTurgut** [comment]
You are right. Since this is a secret and important key, we should create a config file to hold these values.

**Comment by veyisTurgut** [comment]
Status update: 
* added `python-dotenv==0.17.1` to requirements.
* created `.env` file and put secret keys as key-value pair
* in necessary files, imported dotenv typing: `from dotenv import load_dotenv`
* in the function loaded keys typing: `load_dotenv(".env")`
* finally read the values typing: `os.getenv('key_name')`

**Comment by veyisTurgut** [comment]
Staus update:

* Removed the changes made above.
* Embedded Environment variables to `docker-compose.yml` file.
