### ISSUE TITLE
Evaluation of tools and processes 

### ISSUE THREAD

**Issue by Refref18** [bounswe/2021SpringGroup12#168]
Evaluation of tools and processes for the milestone 2
Deadline:09.06 23.59

**Comment by veyisTurgut** [comment]
@gokayyildiz  which tools are you going to write?
I used 
* VSCode
* Pycharm
* Postman
* AWS
* Beekeeper Studio

effectively. Don't forget to add these to the report. I can supply necessary info about these apps.

**Comment by gokayyildiz** [comment]
Thank you, I will ask you the details and will communicate with others to see if there are any extra like yours

**Comment by gokayyildiz** [comment]
I have made the list and written the required comments send slack to be reviewed by team members

**Comment by gokayyildiz** [comment]
Reviews and additions are made by team members. Added to milestone report
