### ISSUE TITLE
List of deliverables 

### ISSUE THREAD

**Issue by Refref18** [bounswe/2021SpringGroup12#193]
List of deliverables for milestone 2 report should be ready before sunday night

**Comment by Refref18** [comment]
![image](https://user-images.githubusercontent.com/51854114/121790011-930c3e80-cbe3-11eb-9ffb-a30016943f5e.png)

**Comment by veyisTurgut** [comment]
Are you sure that we delivered "post and get methods for api" before deadline?

Correct me if I'm wrong but I remember that we missed the deadline.

**Comment by batuhanovski** [comment]
It looks fine generally.

**Comment by batuhanovski** [comment]
I agree with Veyis, the "post and get methods for api" delivered late.

**Comment by Refref18** [comment]
@veyisTurgut  I took this pull request date as reference after that all pull requests are one with frontend and unitetest etc https://github.com/bounswe/2021SpringGroup12/pull/131

**Comment by veyisTurgut** [comment]
Ok, that pr is merged on 01.06.2021. We may miss the deadlines, that's Ok. not a big deal

**Comment by Refref18** [comment]
okey I am making the change thougth that the last change is made 16 days ago .

**Comment by Refref18** [comment]
added to M2 with requested modifications
