### ISSUE TITLE
Editing Issuies Document 

### ISSUE THREAD

**Issue by Refref18** [bounswe/2021SpringGroup12#196]
in https://github.com/bounswe/2021SpringGroup12/wiki/Practice-app-Documentation the format of issues are not in wiki form and not readable, I tried to edit it but didn't work

**Comment by veyisTurgut** [comment]
I didn't get it, can you elaborate?

**Comment by veyisTurgut** [comment]
What is the relation between "API documentation wiki page" and issue format?

**Comment by veyisTurgut** [comment]
Aha I get it. You mean "/issues/" endpoint. Bu that's not my endpoint. Tell it to @litityum

**Comment by litityum** [comment]
Issue handled. There was missing enter which collapses the endpoints' documentations.
