### ISSUE TITLE
Reviewing Executive summary and Project Plan

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/2021SpringGroup12#198]
Executive summary is written by Berk
Project Plan is created by Ömer
They requested a review and approval for their parts.

**Comment by veyisTurgut** [comment]
Reviewed and made necessary changes. 👍🏼

**Comment by Refref18** [comment]
@litityum request for changes of dates

**Comment by batuhanovski** [comment]
I reviewed it while arranging the M2 Group Report, it looks pretty fine after the changes.
