### ISSUE TITLE
Meeting about the preparation of the M2 group report

### ISSUE THREAD

**Issue by batuhanovski** [bounswe/2021SpringGroup12#200]
Meeting for merging all of the works, giving feedbacks, preparing the deliverables part and consequently; making the form of our report suitable to M2 Group Report.

**Comment by batuhanovski** [comment]
We completed the Executive Summary, Project Plan, Evaluation of Tools and Processes parts substantially.
Now, waiting for the individual work done summary for each team member.

After that, we have to deal with the deliverables part.

**Comment by ihsangkcl** [comment]
We have completed all the parts. The group report submitted to moodle by our communicator.
