### ISSUE TITLE
Writing lessons learned team page

### ISSUE THREAD

**Issue by veyisTurgut** [bounswe/2021SpringGroup12#213]
I see that we created our personal "lessons learned" pages. We are supposed to create a page for the team too. Who is volunteer?
@ihsangkcl @batuhanovski @gokayyildiz 

You can find detailed information on moodle-lecture slides

**Comment by gokayyildiz** [comment]
Done, you can review and close the issue

**Comment by gokayyildiz** [comment]
https://github.com/bounswe/2021SpringGroup12/wiki/Lessons_Leaned_Group12 
I also added links to the sidebar on wikipage

**Comment by veyisTurgut** [comment]
That's good, thanks a lot.
