### ISSUE TITLE
Revising requirements 

### ISSUE THREAD

**Issue by veyisTurgut** [bounswe/2021SpringGroup12#235]
**Description**
- In [meeting 3](https://github.com/bounswe/2021SpringGroup12/wiki/Meeting-%233-(26.10.2021)), we got feedback from Zeynep Hoca. Details are in meeting notes. Requirements must be revised regarding that notes.

**Deadline**
- 01.11.2021, 23:59

**External links**
- https://github.com/bounswe/2021SpringGroup12/wiki/Meeting-%233-(26.10.2021)
- https://github.com/bounswe/2021SpringGroup12/wiki/Requirements

**Comment by veyisTurgut** [comment]
Here is what is done to each point:
**1.1.1.3 Expand searching, how?** -> Couldn't do it. 
**1.1.1.15 Remove editing.** -> Done.
**1.1.5.3 There is a confusion about the actor of the action. This requirement should be under system reqs.** -> Moved to 1.2.3.4.
**1.2.1.1 Same issue as above. This requirement should be under user reqs.** -> Moved to 1.1.3.17
**2.2.2 Move under functional reqs.**  -> Moved to 1.2.7
**2.3 Clearly define "modern" browsers. Non functional reqs must be verifiable.** -> Specified 5 modern browsers' early 2021 versions. Also specified Android version.

* All done except 1.1.1.3. @yamanogluberk your support is requested on this requirement. As a backend developer, I couldn't envision how would this requirement would be achieved in UI. You, as a experienced Android developer, would explain this requirement better.
* @yamanogluberk, also review other changes.

**Comment by yamanogluberk** [comment]
1.1.1.3 -> Split into 2 requirements (1.1.1.3, 1.1.1.4), since searching for users and searching for goals have different functionalities. Functionality details are provided.
2.3 -> Android min SDK is changed to 21 as it is recommended by Android
Fixed a few typos
Reviewed and approved changes
