### ISSUE TITLE
Adding the "study for W3C standarts" to project plan

### ISSUE THREAD

**Issue by veyisTurgut** [bounswe/2021SpringGroup12#236]
**Description**
- As Zeynep Hoca said on [Tuesday lab](https://github.com/bounswe/2021SpringGroup12/wiki/Meeting-%233-(26.10.2021)), studying these new topics will take considerable time. Therefore it should be added to the project plan.

.pod file of project plan should be updated and be sent to @batuhanovski. 

**Deadline**
- 01.11.2021, 23:00

**Comment by veyisTurgut** [comment]
.pdf file is sent to @batuhanovski on Slack channel. He will convert pdf to image and will upload it to wiki page.

**Comment by batuhanovski** [comment]
.jpg file has been created.
![new-newplan (1)](https://user-images.githubusercontent.com/63856065/139804315-6d9d1caa-f99b-48ad-aa15-5e9236dd1742.jpg)
