### ISSUE TITLE
Android Login Page

### ISSUE THREAD

**Issue by yamanogluberk** [bounswe/2021SpringGroup12#246]
- Init Android Network Connection structure
- Create Android Login Page
- Connect Login Page to related Backend endpoints
- Use this task for @Refref18 and @ihsangkcl to see an example development process

**Comment by veyisTurgut** [comment]
Don't forget password reset page.

Add a "forgot password?" button, when they click that button, backend team will send a mail. Using the token in mail, users can reset their passwords.

**Comment by yamanogluberk** [comment]
Lets create another issue for forget password @veyisTurgut
