### ISSUE TITLE
Backend Get Request Content-Type Bug

### ISSUE THREAD

**Issue by litityum** [bounswe/2021SpringGroup12#268]
**Bug description**
- When sending a get request to any endpoint without 'Content-Type': 'application/json' header Backend returns Unsupported Media Type.

**Steps to reproduce the bug**
1- Send a get request without Content-Type set to json

**What is the expected result?**
- `[
    {
        "id": 1,
        "goalType": "GOAL",
        "title": "title",
        "isDone": false,
        "description": "deneme",
        "deadline": null,
        "createdAt": null
    }
]`

**What is the actual result?**
- `{
    "timestamp": "2021-11-14T14:48:02.569+00:00",
    "status": 415,
    "error": "Unsupported Media Type",
    "path": "/goals/of_user/1"
}`

**Any additional details / screenshost**
- Also there is an issue with axios: https://github.com/axios/axios/issues/86 . In order to set content-type in axios request, data must be set.

**Comment by veyisTurgut** [comment]
Fixed this in this commit: https://github.com/bounswe/2021SpringGroup12/pull/276/commits/b4145f43ba1bba04d2639b1461d770802d7b6099
