### ISSUE TITLE
Backend returned entity data shouldnt include List<entity>

### ISSUE THREAD

**Issue by yamanogluberk** [bounswe/2021SpringGroup12#278]
**Bug description**
- Having List<entity> in the returned entity data is dangerous because two entities might have links to each other which results in a infinite loop.
- Instead of returning the whole entity object in the List as sublinks of an entity, the server should return a smaller entity object which only includes the title and the id of the entity. This smaller object will be used to display descriptive information of an entity without having to go to the details page of that entity.

**Comment by veyisTurgut** [comment]
Don't worry. It returns EntitiDTO and EntitiDTO object does not have Sublinks field. So this will not cause an infinite loop

**Comment by veyisTurgut** [comment]
Here is an example return: 
[
    {
        "id": 202,
        "mainGoal_id": null,
        "entitiType": "SUBGOAL",
        "title": "fg",
        "description": "strinsg",
        "createdAt": "2021-11-11T17:26:26.071+00:00",
        "isDone": true,
        "deadline": "2021-11-11T17:26:26.071+00:00",
        "rating": 2.0,
        "period": null,
    },
    {
        "id": 53,
        "mainGoal_id": null,
        "entitiType": "SUBGOAL",
        "title": "75",
        "description": "457",
        "createdAt": null,
        "isDone": true,
        "deadline": "2021-11-11T16:35:31.026+00:00",
        "rating": null,
        "period": null,
    }
    ]
