### ISSUE TITLE
GetExisting<Entities>endpoints needed

### ISSUE THREAD

**Issue by yamanogluberk** [bounswe/2021SpringGroup12#283]
**Describe the problem which caused your suggestion/solution**
- When a user wants to link an existing entity to another one, we should be able to show them which currently existing entities.
- Endpoints should be created for each entity: Subgoals, Tasks, Routines, Questions, Reflections

**Describe the suggestion/solution**
- Endpoints for each entity type should be created that returns all existing respective entities belonged to the user.

**Comment by veyisTurgut** [comment]
Fixed here: https://github.com/bounswe/2021SpringGroup12/pull/284
