### ISSUE TITLE
Null fields while getting entity info

### ISSUE THREAD

**Issue by litityum** [bounswe/2021SpringGroup12#287]
**Bug description**
- While requesting info of an entity some fields return null

**Steps to reproduce the bug**
1- get request to /entities/{goal_id}
2- get request to /entities/task/{entity_id}

**What is the expected result?**
- ` {
        "id": 57,
        "mainGoal_id": 12,
        "entitiType": "ROUTINE",
        "title": "routine title",
        "description": "routine descr",
        "createdAt": tarih,
        "isDone": false,
        "deadline": null,
        "rating": null,
        "period": null
    },`

**What is the actual result?**
-  {
        "id": 57,
        "mainGoal_id": null,
        "entitiType": "ROUTINE",
        "title": "routine title",
        "description": "routine descr",
        "createdAt": null,
        "isDone": false,
        "deadline": null,
        "rating": null,
        "period": null
    },

**Any additional details / screenshost**
- 
![image](https://user-images.githubusercontent.com/38630218/141856316-20229f8e-36d7-4d99-ab71-b7f4cecd8cc1.png)

**Comment by burakcankazim** [comment]
Fixed with PR #288
