### ISSUE TITLE
Add Group Goal option to the ‘Create Goal Page’ - Android 

### ISSUE THREAD

**Issue by yamanogluberk** [bounswe/2021SpringGroup12#312]
**Description**
- Add the option to view and to request data
- The option should be selected when opened from ‘group goals page’ and not selected when opened from ‘goals page’
- The above can be done using arguments when openning the fragment, examples exist in the project
- Make the necessary changes on the request

**Comment by Refref18** [comment]
All done in https://github.com/bounswe/2021SpringGroup12/pull/370 and merged to android/dev
