### ISSUE TITLE
Create ‘Group Goals Page’  Android

### ISSUE THREAD

**Issue by yamanogluberk** [bounswe/2021SpringGroup12#313]
**Description**
- Create ‘Group Goals Page’ 
- Make requests, connect the data
- Connect item on click to ‘Group Goal detail Page’ for the goal list - Dependent on #314 
- Add it to the second page of the bottom navigation bar
- Change the icon on bottom bar
- The page structure should be similar with 'Goals Page'(Home Page)
- The add button on top should open ‘create goal page’ with group mode already selected - Dependent on #312

**Comment by Refref18** [comment]
you can see:https://github.com/bounswe/2021SpringGroup12/pull/370
