### ISSUE TITLE
Uploading the latest meeting note

### ISSUE THREAD

**Issue by veyisTurgut** [bounswe/2021SpringGroup12#326]
**Description**
- I was unable to attend the last lab. Upload the meeting notes to [wiki](https://github.com/bounswe/2021SpringGroup12/wiki) page, so I can catch up. If you don't know the general structure, here is the [template]( https://github.com/bounswe/2021SpringGroup12/wiki/Meeting-Template)

**Deadline**
- 03.12.21, 22:00

**Comment by veyisTurgut** [comment]
I conclude that nobody took notes, even didn't care to say it. Great!

**Comment by yamanogluberk** [comment]
https://github.com/bounswe/2021SpringGroup12/wiki/Meeting-%237--(30.11.2021) @veyisTurgut  it is upload now, @litityum shared it with us previously but we should have uploaded it to the wiki as well.
