### ISSUE TITLE
Add resource feature to goals and entities

### ISSUE THREAD

**Issue by litityum** [bounswe/2021SpringGroup12#331]
**Description**
- Users shall be able to add resources such as images to goals and entities.

**Deadline**
- 12.12.2021

**Comment by batuhanovski** [comment]
The resource structure is determined, the visual representation will be shared

**Comment by batuhanovski** [comment]
Tried many "resource displaying methods" and still searching for a proper method.

**Comment by batuhanovski** [comment]
Some updates in the Goal Page and Entity Pages has done.
An example of an entity page: 
![Screen Shot 2021-12-11 at 17 21 45](https://user-images.githubusercontent.com/63856065/145679955-7b1a0e8e-2444-446f-b8a8-74cb4b83c8b7.png)

**Comment by batuhanovski** [comment]
Delete Resource feature will be implemented later (probably tomorrow)

**Comment by batuhanovski** [comment]
To resource displaying is also needs more work, for now the output shape is arraybuffer form. Searched some ways to display the image proper, but it is not completed yet.
![WhatsApp Image 2021-12-11 at 17 17 38](https://user-images.githubusercontent.com/63856065/145682325-038b1c3e-d122-488a-86e3-0fda539aea5e.jpeg)

**Comment by batuhanovski** [comment]
At today's meeting, it is decidied that the resource adding feature will be on the entity page. So, cahges will be implemented.

**Comment by batuhanovski** [comment]
Everything is done, users can upload their resources, but there is a situation at displaying them, [#364](https://github.com/bounswe/2021SpringGroup12/issues/364) is about it. So, this issue will be closed
