### ISSUE TITLE
Entity Link Issue - Backend

### ISSUE THREAD

**Issue by yamanogluberk** [bounswe/2021SpringGroup12#333]
**Bug description**
- One entity should be linked to multiple entities/subgoals but it can only have one parent goal. However, currently it can only be linked to one subgoal.

**Comment by veyisTurgut** [comment]
Deadline: 06.12.21, 20:00

**Comment by veyisTurgut** [comment]
Couldn't manage the time, will handle it until 9.12.21

**Comment by veyisTurgut** [comment]
This is implemented in #458
