### ISSUE TITLE
Creating "technologies used" page on wiki

### ISSUE THREAD

**Issue by veyisTurgut** [bounswe/2021SpringGroup12#335]
**Description**
- According to [ meeting #7](https://github.com/bounswe/2021SpringGroup12/wiki/Meeting-%237--(30.11.2021)) we should create a technologies used page. You can use [milestone report](https://github.com/bounswe/2021SpringGroup12/blob/master/deliverables/CM1-Group12.pdf) to check what we have used. Also, you can inspired from previous years' wiki pages.

**Deadline**
- 07.12.21, 13:00

**Comment by veyisTurgut** [comment]
@aberatcan you missed the deadline!

**Comment by aberatcan** [comment]
- Page was created and added to 'Requirements' section in wiki page sidebar => [Used Technologies](https://github.com/bounswe/2021SpringGroup12/wiki/Used-Technologies)
