### ISSUE TITLE
Subgoal/Entity Creation Ambiguity- Backend

### ISSUE THREAD

**Issue by yamanogluberk** [bounswe/2021SpringGroup12#343]
**Description**
- I think there is an ambiguity while creating a subgoal under a goal or another subgoal.

**What We Need**
We need to be able to create a subgoal under a goal or another subgoal.

** Problem **
For creating a subgoal this is the object expected from us:
`{
  "deadline": "2021-12-07T23:02:31.653Z",
  "description": "string",
  "main_goal_id": 0,
  "main_groupgoal_id": 0,
  "parent_subgoal_id": 0,
  "title": "string"
}`

With this kind of request it is not clear how we can create a subgoal under another subgoal or under the main goal or under a group goal, since all 3 ids are expected in the request.

**Suggested Solution**
Instead of sending 3 ids we can send only one id as the parent id and denote the type of the parent in another field.

**Comment by veyisTurgut** [comment]
This is the endpoint for creating a subgoal under a goal. ![image](https://user-images.githubusercontent.com/47869761/145120802-e843d0f4-a87a-4b99-9852-6d08ff248ca7.png)
* You should only fill main_goal_id. 
* main_group_goal_id and parent_subgoal_id is not needed.

This is the endpoint for creating a subgoal under another subgoal: ![image](https://user-images.githubusercontent.com/47869761/145120891-3a9e002f-6a1b-46af-818e-67e2981a6eb4.png)
* You should only fill parent_subgoal_id
* main_groupgoal_id and main_goal_id can be blank.

@yamanogluberk

**Comment by veyisTurgut** [comment]
I tried to configure swagger to highlight necessary fields and optional fields, bur couldn't figure it out. Sorry for the confusion.

**Comment by veyisTurgut** [comment]
Don't hesitate to contact for confusing parts.

**Comment by yamanogluberk** [comment]
Thanks, let me try it out and I will update the status

**Comment by veyisTurgut** [comment]
Can we close this @yamanogluberk ?

**Comment by yamanogluberk** [comment]
Is it okey for me to send unnecessary fields as well? Because on java the default value of int is 0 and since we have these fields on the object I assume it is going to send these fields as 0 as well. @veyisTurgut

**Comment by veyisTurgut** [comment]
Oh, I see. Could you make them -1?
Don't make me change the whole code base 🙂

**Comment by veyisTurgut** [comment]
* Oh, I see that you are right! 
* Setting other fields to -1 can work in subgoal creation but will fail in entity creation.
* I will implement it as you stated: `Instead of sending 3 ids we can send only one id as the parent id and denote the type of the parent in another field.`
* New entity creation endpoint json content is : `{
  "deadline": "2021-12-11T20:19:01.795Z",
  "description": "string",
  "parentType":[ NONE, SUBGOAL, GOAL, GROUPGOAL, ENTITY ],
  "parent_id": 0,
  "title": "string"
}`

**Comment by veyisTurgut** [comment]
Fixed it in [this commit](https://github.com/bounswe/2021SpringGroup12/pull/348/commits/3c70a2903dd66261ff81b59b87a2866a14667ad1). Wait for merge and deployment @yamanogluberk

**Comment by yamanogluberk** [comment]
It works as you suggested!
