### ISSUE TITLE
Creating an endpoint which gets all entities including subgoals 

### ISSUE THREAD

**Issue by batuhanovski** [bounswe/2021SpringGroup12#345]
**Bug description**
- There was no endpoint to get all the children entities of a goal including subgoals'

**Steps to reproduce the bug**
1- This endpoint can be created.

**Comment by veyisTurgut** [comment]
On it.

**Comment by veyisTurgut** [comment]
Opened a pull request on #346, check it out @batuhanovski. You can use it after @burakcankazim merges it.
