### ISSUE TITLE
Create all requests for Group Goal

### ISSUE THREAD

**Issue by Refref18** [bounswe/2021SpringGroup12#353]
**Description**
- Creating all requests in serverAPI that are mentioned in group goal section in swagger:http://3.144.201.198:8085/swagger-ui.html#/

**Comment by Refref18** [comment]
should I create a brand new fragment for deleting the group goal? @yamanogluberk

**Comment by Refref18** [comment]
where the "Get all group goals created by a user." request will be used? @veyisTurgut

**Comment by veyisTurgut** [comment]
If it's unnecessary, ignore it. I though it would be useful.

**Comment by yamanogluberk** [comment]
@Refref18 We dont have a clear requirement for this feature, you can do as you see fit for now, and later we can discuss with the customer and with the team

**Comment by yamanogluberk** [comment]
Closed the issue by mistake, please ignore it!

**Comment by Refref18** [comment]
All necessery requests are created and the data is connected. See: https://github.com/bounswe/2021SpringGroup12/pull/370
