### ISSUE TITLE
Return type of Group Goal Members 

### ISSUE THREAD

**Issue by Refref18** [bounswe/2021SpringGroup12#356]
**Description**
-/v2/groupgoals/{groupgoal_id} :Get a Group Goal is returning just the id's of the group members but we need usernames

**Comment by veyisTurgut** [comment]
* First of all as, I stated [here](https://github.com/bounswe/2021SpringGroup12/issues/353#issuecomment-991793429), Burakcan wrote Group Goal endpoints. I don't know in detail. It will be better if you ask him.
* But let me check. I will update here if I can fix it.

**Comment by veyisTurgut** [comment]
* Ah it's easy to fix. I'll handle in a few minutes.

**Comment by veyisTurgut** [comment]
@Refref18 pr #357 fixes this issue.

**Comment by veyisTurgut** [comment]
* It returns ` "members": [
    {
      "user_id": 23,
      "username": "string1",
      "password": null,
      "email": null
    }
  ]` object now, instead of `[
    {
      "id": 23,}
  ]`
