### ISSUE TITLE
Login Update

### ISSUE THREAD

**Issue by Refref18** [bounswe/2021SpringGroup12#363]
**Description**
- Users are able to register with an invalid email address such as "r" One shoul only be able to register with a valid email address.

**Comment by veyisTurgut** [comment]
* I'm aware of that. 
* I want to use validation annotators. But they are not working, I even opened an issue opened this previously: [#334](https://github.com/bounswe/2021SpringGroup12/issues/334)
* @burakcankazim will fix it, I hope.

**Comment by Refref18** [comment]
now it is fixed and working properly
