### ISSUE TITLE
Leaving Group Goal Feature 

### ISSUE THREAD

**Issue by Refref18** [bounswe/2021SpringGroup12#367]
**Description**
- Add leaving group goal feature
- Add a button to relative UI's 
- Make the connections and rearragenge service.API

**Comment by Refref18** [comment]
The leave member feature is initialized in pull request: https://github.com/bounswe/2021SpringGroup12/pull/370
But there has to be a arrange in backend: When a user who creates the group goal tries to leave the goal it gives an error.

**Comment by veyisTurgut** [comment]
* I did not write this code.
* Maybe Burakcan wanted it like this, no idea.

**Comment by burakcankazim** [comment]
Yes, I thought that creator wouldn't be able to leave his goal, only delete it. But I can change the design if it is needed.
