### ISSUE TITLE
Adding Frontend Related Pages to M2

### ISSUE THREAD

**Issue by batuhanovski** [bounswe/2021SpringGroup12#412]
**Description**
- Frontend Related Pages has to bre created and shared.

**Deadline**
- 18.12.2021

**External links**
- https://docs.google.com/document/d/181lEM8QXojeQNlKGr1wcZzJoS502Rh0PZ87E2QVOpSI/edit?usp=sharing

**Comment by batuhanovski** [comment]
Screenshots of new implementations are added to the doc.

**Comment by litityum** [comment]
Links are added to doc
