### ISSUE TITLE
Implementing search -- android

### ISSUE THREAD

**Issue by veyisTurgut** [bounswe/2021SpringGroup12#420]
**Description**
- There are three different search endpoints: 
  - for username
  - for goals with simple queries that looks only titles and description
  - for tags which returns goals that include the tags and similar tags
  
**Suggestion/Solution**
- Tag search is a bit slow and may be frustrating. Instead of making them wait on the load screen, show them the second option described above as we discussed previously. 

**Related Info**
* Search endpoint foor users: /v2/users/search/{query}
* Search endpoint for goals exact match: /v2/goals/search?query=
* Search endpoint for tags: /v2/goals/search/{tag}

**Comment by veyisTurgut** [comment]
Please note that I-CD is not working. So it does not deployed. I don't know why it's off. Please contact Burakcan

**Comment by veyisTurgut** [comment]
I will implement search for prototypes shortly.

**Comment by yamanogluberk** [comment]
@Refref18 and @ihsangkcl  have implemented different search features, they can update the issue.

**Comment by ihsangkcl** [comment]
https://github.com/bounswe/2021SpringGroup12/pull/467 User search is here.
