### ISSUE TITLE
Implementing search -- frontend

### ISSUE THREAD

**Issue by veyisTurgut** [bounswe/2021SpringGroup12#421]
**Description**
- There are three different search endpoints: 
  - for username
  - for goals with simple queries that looks only titles and description
  - for tags which returns goals that include the tags and similar tags
  
**Suggestion/Solution**
- Tag search is a bit slow and may be frustrating. Instead of making them wait on the load screen, show them the second option described above as we discussed previously. 

**Related Info**
* Search endpoint foor users: /v2/users/search/{query}
* Search endpoint for goals exact match: /v2/goals/search?query=
* Search endpoint for tags: /v2/goals/search/{tag}

**Comment by litityum** [comment]
This feature was implemented in https://github.com/bounswe/2021SpringGroup12/pull/543 by @aberatcan
