### ISSUE TITLE
Market Place 

### ISSUE THREAD

**Issue by Refref18** [bounswe/2021SpringGroup12#427]
**Description**
- Creating the UI design of Market Place and listing all published goals, making neccessary connections

**Comment by Refref18** [comment]
In prototypes wouldn't it be better also to return the username of the owner of the goal? @veyisTurgut

**Comment by veyisTurgut** [comment]
Good idea!
Will implement immediately. @Refref18

**Comment by veyisTurgut** [comment]
It's implemented in this commit : https://github.com/bounswe/2021SpringGroup12/pull/419/commits/f6254a6297a718c5484277bc214bc2a444754820

Will be deployed shortly.

**Comment by Refref18** [comment]
in following commit: https://github.com/bounswe/2021SpringGroup12/commit/60d1c2e44a5f47d9152d55ea43a326cae1145717 , the usernames of published prototypes can be seen

**Comment by Refref18** [comment]
the whole market place is implemented in following pr:https://github.com/bounswe/2021SpringGroup12/pull/432

**Comment by veyisTurgut** [comment]
Proud!
