### ISSUE TITLE
Publish Goal

### ISSUE THREAD

**Issue by Refref18** [bounswe/2021SpringGroup12#429]
**Description**
- Making necessary arrangements in goal page for user to publish his/her goals
-  Making necessary connections with API

**Comment by Refref18** [comment]
"publish my goal" button is added but do we call it "publish" or something else in UI? Frontend team, what did you call it in UI page @litityum @batuhanovski @aberatcan

**Comment by Refref18** [comment]
publish my goal button is able but will there be an update publish feature so that I can edit the button @veyisTurgut @burakcankazim

**Comment by veyisTurgut** [comment]
There will be! Tomorrow or the day after -- hopefully.

**Comment by aberatcan** [comment]
> "publish my goal" button is added but do we call it "publish" or something else in UI? Frontend team, what did you call it in UI page @litityum @batuhanovski @aberatcan

I created an issue for that #463 Will be implemented soon!

**Comment by Refref18** [comment]
implemented in following pr:https://github.com/bounswe/2021SpringGroup12/pull/511
