### ISSUE TITLE
Response of /v2/prototypes/

### ISSUE THREAD

**Issue by Refref18** [bounswe/2021SpringGroup12#430]
**Description**
- the API is returning all the information of goals but in market place page we only need username, title and description

**Comment by veyisTurgut** [comment]
I need to write at least 7 different class for that to happen. Considering limited time we have, just show the users what you prefer. @Refref18

**Comment by veyisTurgut** [comment]
Maybe @burakcankazim can implement.

**Comment by Refref18** [comment]
I arranged my code accordingly
