### ISSUE TITLE
Icon for market place

### ISSUE THREAD

**Issue by Refref18** [bounswe/2021SpringGroup12#433]
**Description**
- Selection of icon for market place

**Comment by Refref18** [comment]
![image](https://user-images.githubusercontent.com/51854114/147498333-f364dd26-3172-47dd-8331-30dff16a7dfc.png)
I picked up this icon for the market place icon, which was called "web" to have parallel android and frontend design I urge frontend group to use the same icon @litityum @batuhanovski , and I will appreciate if one of you approve the icon @yamanogluberk

**Comment by batuhanovski** [comment]
okay! wonderful choice

**Comment by litityum** [comment]
It seems well!
