### ISSUE TITLE
Number of Downloads 

### ISSUE THREAD

**Issue by Refref18** [bounswe/2021SpringGroup12#451]
**Description**
- Users should be able to view number of downloads of each goal that is published

**Comment by Refref18** [comment]
what is the type of download_count? It returns 0 sometimes but it also returns null time to time as well. @veyisTurgut

**Comment by veyisTurgut** [comment]
I updated it yesterday, so goals-prototypes created the before my update won't have those fields naturally. A database cleaning can solve this. Or even better, I will implement unpublish endpoint tomorrow.

**Comment by veyisTurgut** [comment]
Type is Long(int64) by the way @Refref18

**Comment by veyisTurgut** [comment]
ah this is not a backend issue assigned to me, sorry for the confusion. will open it again.

**Comment by Refref18** [comment]
number of downloads is fixed thanks to reseting database now it works in the following pr:https://github.com/bounswe/2021SpringGroup12/pull/506
