### ISSUE TITLE
Adding Tag Bug

### ISSUE THREAD

**Issue by batuhanovski** [bounswe/2021SpringGroup12#471]
**Bug description**
- After adding tags to a goal, the endpoint comes with null

**Steps to reproduce the bug**
1- Corresponding endpoint can be investigated.

**Comment by veyisTurgut** [comment]
As software gets larger, harder it becomes to add new features...

I forgot to add this one liner: `goalGetDTO.setTags(goal.getTags().stream().map(x->x.getName()).collect(Collectors.toSet()));`

It will be fixed in a few minutes. Thx for the warning @batuhanovski

**Comment by veyisTurgut** [comment]
Fixed in #472
