### ISSUE TITLE
Can't follow more than 1 people.

### ISSUE THREAD

**Issue by ihsangkcl** [bounswe/2021SpringGroup12#483]
**Bug description**
- I can't follow more than 1 user at the same time.

**Steps to reproduce the bug**
1- Follow a user 
2- Try to follow another user 
3- Error occurs
4- Unfollow first user.
5- Now, you can follow the user at step 2.

**What is the expected result?**
- User should be able to follow more than 1 people

**What is the actual result?**
- User can follow only 1 people

**Comment by veyisTurgut** [comment]
Fixed here: #485
