### ISSUE TITLE
Adding name and surname fields for sign-in

### ISSUE THREAD

**Issue by Refref18** [bounswe/2021SpringGroup12#489]
**Description**
-Name and surname fields will be added to backend according to requirement: Guests shall enter their e-mail, name, surname, username and a password in order to sign up.

**Comment by veyisTurgut** [comment]
* Thanks for opening the issue as we went through the requirements this morning and identified unimplemented ones. 
* Also, sorry for being this late, eduroam fixed just now. Will do this in a couple of minutes.

**Comment by veyisTurgut** [comment]
Implemented in #496
