### ISSUE TITLE
Adding popular goals 

### ISSUE THREAD

**Issue by Refref18** [bounswe/2021SpringGroup12#490]
**Description**
-Popular goals will be added to backend

**Comment by veyisTurgut** [comment]
Fixed in #496

**Comment by Refref18** [comment]
#496 is not about the popular goals and I couldn't find in swagger as well

**Comment by veyisTurgut** [comment]
* [This commit](https://github.com/bounswe/2021SpringGroup12/pull/496/commits/8dc4bb3b25adde66e59932bef4420dd169dc109f) in #496 is about the popular goals. Look carefully.
* There is no direct popular goal search is implemented, rather normal search results sorted with respect to popularity.
