### ISSUE TITLE
Displaying group goals has a problem

### ISSUE THREAD

**Issue by batuhanovski** [bounswe/2021SpringGroup12#518]
**Bug description**
- Display of the group goals is problematic. like this: 
![Screen Shot 2022-01-03 at 21 26 51](https://user-images.githubusercontent.com/63856065/147966190-6651cf3b-91bb-4965-9b59-7ccbbffc66f3.png)

**Steps to reproduce the bug**
1- I think it might because of the addGoal, because the title's of the created goals are null in here:
![Screen Shot 2022-01-03 at 21 26 56](https://user-images.githubusercontent.com/63856065/147966260-a26b8ca6-90de-43f6-8f5e-1fca727b73a8.png)

**Comment by burakcankazim** [comment]
Fixed it in #521 's last commit

**Comment by litityum** [comment]
It was fixed but there were some problems while viewing a goal. I have fixed them in the pr: https://github.com/bounswe/2021SpringGroup12/pull/532
