### ISSUE TITLE
Missing Linking Feature for Entities - Backend

### ISSUE THREAD

**Issue by yamanogluberk** [bounswe/2021SpringGroup12#523]
**Description**
We should be able to link entities to 'GOAL' or 'GROUPGOAL' as well.

- 'LinkType' currently only has 'Subgoal' and 'entiti' options, above options should be added.
- 'entities' field in 'goal' objects should contain linked entities, not all entities of the goal.
- GetAllEntitiesOfAGoal and GetAllEntitiesOfAGroupGoal endpoints should be added to return all entities of the goal after the previous change.

**Comment by burakcankazim** [comment]
Implemented in PR #525.
