### ISSUE TITLE
Complete existing software systems analysis table!

### ISSUE THREAD

**Issue by veyisTurgut** [bounswe/2021SpringGroup12#59]
Until 08.04.2021, 23.59. 
Tables are ok, but "plusses" part is missing.

**Comment by veyisTurgut** [comment]
Done.

Here is the link : https://github.com/bounswe/2021SpringGroup12/wiki/Related-Softwares-Tables

@ihsangkcl  take a look at it.

**Comment by ihsangkcl** [comment]
Good work, as always.:+1:
