### ISSUE TITLE
Revise the requirements page!

### ISSUE THREAD

**Issue by veyisTurgut** [bounswe/2021SpringGroup12#77]
Deadline 22.04.2021 @21:00

Since customer wants some new features, we must revise requirements page regarding new functionalities.

**Comment by veyisTurgut** [comment]
https://github.com/bounswe/2021SpringGroup12/wiki/Requirements
@Refref18 @ihsangkcl check it out. There might ve sth I've missed.

**Comment by Refref18** [comment]
Reviewed, the comments are on your slack account!

**Comment by veyisTurgut** [comment]
Took actions with respect to those comments!
