### ISSUE TITLE
Adding new Requirements 

### ISSUE THREAD

**Issue by Refref18** [bounswe/2021SpringGroup12#87]
Additional requirements will be added according to meeting notes

**Comment by veyisTurgut** [comment]
https://github.com/bounswe/2021SpringGroup12/wiki/Requirements
@ihsangkcl check it out. You may use revision history for the newly added ones.

**Comment by ihsangkcl** [comment]
OK. I will check it before meeting. 👍

**Comment by ihsangkcl** [comment]
I reviewed it. We have talked about some points with @veyisTurgut . Done.
